shared:
    image: betaskopesb:stable
    settings: 
       email:
          addresses: [arun.p@netskope.com]
          statuses: 
               - SUCCESS
               - FAILURE
               - ABORTED
               - QUEUED
               - RUNNING


jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps: 
            - test-connectivity: touch /tmp/SD-success
            - execute a job:  su - ansible -C "/infrastructure/automation/scripts/ansible-apt.sh -h pyrproxy -i /opt/ns/automation-53.1.0/automation/inventory/betaskope.local -r 53.1.0"
