shared:
    image: bsdeployready:latest

jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps: 
            - copy-ssh-key: add id_bstest ~/.ssh/ 
            - copy-pub-key: add id_bstest.pub ~/.ssh/ 
            - setup-connection: ssh ansible@apiconnectorfmaggcmr01.betaskope.local
            - test-connectivity: touch /tmp/SD-success
