shared:
    image: ubuntu:16.04
jobs:
    main:
        requires: [~pr, ~commit]
        environment: 
           SD_SOURCE_DIR: /sd/workspace/src/github.com/arunpnetskope/bstest/template
        sourcePaths: ["template/", "screwdriver.yaml"]
        steps:
           - echo "hello netskope!"        
